eureka:
  client:
    enabled: false
zuul:
  routes:
    get:
      path: /get/**
      url: http://httpbin.org/get
    studentwiki:
      path: /student-wiki/v0/**
      url: http://hr-student-wiki-staging.herokuapp.com
    instructorwiki:
      path: /instructor-wiki/v0/**
      url: http://hr-instructor-wiki-staging.herokuapp.com
    choreographer:
      path: /choreographer/v0/**
      url: http://rc-choreographer-staging.herokuapp.com
    library:
      path: /library/v0/**
      url: http://rc-library-staging.herokuapp.com
    interviewprompts:
      path: /interview-prompts/v0/**
      url: http://rc-interview-prompt-staging.herokuapp.com
    interviewpromptsshort:
      path: /prompts/**
      url: http://rc-interview-prompt-staging.herokuapp.com
