eureka:
  client:
    enabled: false
zuul:
  routes:
    get:
      path: /get/**
      url: http://httpbin.org/get
    studentwiki:
      path: /student-wiki/v0/**
      url: http://hr-student-wiki-production.herokuapp.com
    staffwiki:
      path: /staff-wiki/v0/**
      url: http://hr-staff-wiki-production.herokuapp.com
    choreographer:
      path: /choreographer/v0/**
      url: http://rc-choreographer-production.herokuapp.com
    library:
      path: /library/v0/**
      url: http://rc-library-production.herokuapp.com
    interviewprompts:
      path: /interview-prompts/v0/**
      url: http://rc-interview-prompt-production.herokuapp.com
    interviewpromptsshort:
      path: /prompts/**
      url: http://rc-interview-prompt-production.herokuapp.com
